### ISSUE TITLE
作るサービスの概要を把握と技術把握

### ISSUE THREAD

**Issue by taishi1116** [kenta-0615/react-weather-app#11]
# やること
- サービスの理解
  - どんな機能があるのか
  - どんなデザインなのか
  - どんなAPIを叩くのか
    - どんなパラメータで叩いて
    - どんなレスポンスが来てなど

- 技術の理解
  - tailwindcss
    - 今回使うCSSなので、これのドキュメント読む 
  - storybook 
    - 今回使う技術なので、これのドキュメントを読む

#  参考文献
- https://tailwindcss.com/
- https://storybook.js.org/

**Comment by taishi1116** [comment]
@kenta-0615 
これずっとTODOにあるのですが、もう手を動かしているのでクローズでいいですか?

**Comment by kenta-0615** [comment]
@taishi1116 
クローズで大丈夫です！

**Comment by taishi1116** [comment]
なら健太がアサイニーズなので自分で閉じてください
