### ISSUE TITLE
スタイルの統一

### ISSUE THREAD

**Issue by kenta-0615** [kenta-0615/react-weather-app#34]
## 内容
- 現在できている画面のスタイルの統一
- スタイルは、Tailwindを使用
## デザイン
<img width="517" alt="スクリーンショット 2022-05-17 20 17 29" src="https://user-images.githubusercontent.com/84606742/176590290-4e1679aa-5146-4b6b-8f54-359d321f9547.png">
<img width="510" alt="スクリーンショット 2022-05-17 21 14 33" src="https://user-images.githubusercontent.com/84606742/176590375-25b77b97-f126-4e8d-ac06-67e6596f8d96.png">

**Comment by taishi1116** [comment]
@kenta-0615 
`assignnes`の意味を理解して自分とせいいちろうを割り当てている?

**Comment by kenta-0615** [comment]
> @kenta-0615 `assignnes`の意味を理解することとせいいちろうをできますか？

書き込み、読み取り等の権限を与えると認識です！
誠一郎くんにも自分の技術共有のつもりでassignnesしてます！

**Comment by taishi1116** [comment]
> 書き込み、読み取り等の権限を与えると認識です！

違うので、ググってください！なんとなくで利用するのではなく、意味を理解して扱う癖つけてー！
英語に意味がわからないなら翻訳するとか、文献見るとかできるはず。。。。

**Comment by kenta-0615** [comment]
> 
自身、該当する Issue またはPull Requestにコメントした任意の人
確認しました。PRした人を乗せるところでした。
認識違ってました。
今後どう意味なのか曖昧なことはググる癖をつけます！

**Comment by taishi1116** [comment]
> 自身、該当する Issue またはPull Requestにコメントした任意の人
確認しました。PRした人を乗せるところでした。

まだ違う気がするよ。PRした人という意味だと誤解がある

**Comment by taishi1116** [comment]
PRした人 = その**チケットの担当者**だよね

**Comment by kenta-0615** [comment]
> まだ違う気がするよ。PRした人という意味だと誤解がある
> PRした人 = そのチケットの担当者だよね

すいません、今理解しました。
もうちょっと理解力鍛えます。

**Comment by taishi1116** [comment]
理解力というより、なんとなくで扱っている姿勢やマインドの改善なんじゃないかな?

「なんとなく割り当てる」or 「たいしが言っているから割り当てる」から、「意味を理解した上で扱う」っていう気持ちになれば自然とわからないことをググるようになって必然と理解に繋がるはず！

そこでググってもわからないなら理解力の問題が次に出てくる感じだと思う

**Comment by kenta-0615** [comment]
> 理解力というより、なんとなくで扱っている姿勢やマインドの改善なんじゃないかな?
> 
> 「なんとなく割り当てる」or 「たいしが言っているから割り当てる」から、「意味を理解した上で扱う」っていう気持ちになれば自然とわからないことをググるようになって必然と理解に繋がるはず！
> 
> そこでググってもわからないなら理解力の問題が次に出てくる感じだと思う

確かに言われているままにやっている感じは、あったように思えます。
何かを扱う前に疑問を持って理解して何事も実行していきたいと思います！
